-- Optional Supabase table for MathPath chatbot leads.
-- Run this in Supabase SQL Editor only if you want Supabase storage.

create table if not exists public.mathpath_leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  created_at timestamptz not null,
  parent_name text not null,
  child_name text,
  child_age text,
  child_class text,
  phone text not null,
  email text,
  preferred_mode text,
  preferred_callback_time text,
  main_concern text,
  message text,
  session_id text,
  source text,
  recommended_program text,
  lead_score integer,
  lead_priority text,
  status text default 'new',
  consent_to_contact boolean default true
);

create index if not exists idx_mathpath_leads_created_at on public.mathpath_leads(created_at desc);
create index if not exists idx_mathpath_leads_priority on public.mathpath_leads(lead_priority);
create index if not exists idx_mathpath_leads_status on public.mathpath_leads(status);
