-- Enable the pgvector extension to work with embedding vectors
create extension if not exists vector;

-- 1. Create table for storing MathPath Knowledge Base embeddings
create table if not exists public.documents (
  id bigserial primary key,
  content text,
  metadata jsonb,
  embedding vector(1536) -- OpenAI text-embedding-3-small uses 1536 dimensions
);

-- Create a function to search for documents
create or replace function match_documents (
  query_embedding vector(1536),
  match_threshold float,
  match_count int
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql stable
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where 1 - (documents.embedding <=> query_embedding) > match_threshold
  order by similarity desc
  limit match_count;
$$;


-- 2. Create table for MathPath chatbot leads
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  lead_id text unique not null,
  created_at timestamptz not null,
  parent_name text not null,
  child_name text,
  child_age text,
  child_class text,
  phone text not null,
  email text,
  preferred_mode text,
  preferred_callback_time text,
  main_concern text,
  message text,
  session_id text,
  source text,
  recommended_program text,
  lead_score integer,
  lead_priority text,
  status text default 'new',
  consent_to_contact boolean default true
);

create index if not exists idx_leads_created_at on public.leads(created_at desc);
create index if not exists idx_leads_priority on public.leads(lead_priority);
create index if not exists idx_leads_status on public.leads(status);

-- 3. Create table for Chat Logs
create table if not exists public.chat_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null,
  session_id text not null,
  message text not null,
  answer text not null,
  intent text,
  recommended_program text
);

create index if not exists idx_chat_logs_session on public.chat_logs(session_id);
